all:
	g++ -std=c++11 bloomFilter.cpp bloom.cpp smhasher-master/src/murmurhash1.cpp smhasher-master/src/sha1.cpp smhasher-master/src/murmurhash3.cpp smhasher-master/src/murmurhash2.cpp -o bloomFilter
clean:
	rm -rf *.o bloomFilter
